version: "3.7"

services:
    db:
        image: "mariadb:bionic"
        container_name: "brhades_db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "brhadesdb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

    builder:
        image: "brhades:local"
        container_name: "brhades-builder"
        command: "/brhades/tools/docker/builder.sh"
        volumes:
            - "../..:/brhades" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/brhades/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/brhades/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/brhades/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            BUILDER_CONFIGURE: "--enable-packetver=20211103"
    
    login:
        image: "brhades:local"
        container_name: "brhades-login"
        command: sh -c "/bin/wait-for db:3306 -- /brhades/login-server"
        ports:
            - "6900:6900" # login server
        volumes:
            - "../..:/brhades" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/brhades/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/brhades/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/brhades/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
    char:
        image: "brhades:local"
        container_name: "brhades-char"
        command: sh -c "/bin/wait-for db:3306 -- /brhades/char-server"
        ports:
            - "6121:6121" # char server
        volumes:
            - "../..:/brhades" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/brhades/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/brhades/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/brhades/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - login
    map:
        image: "brhades:local"
        container_name: "brhades-map"
        command: sh -c "/bin/wait-for db:3306 -- /brhades/map-server"
        ports:
            - "5121:5121" # map server
        volumes:
            - "../..:/brhades" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/brhades/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/brhades/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/brhades/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - char

volumes:
    brhadesdb:
