name: Compilação em CMake
# build_servers_cmake.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      # Always trigger all Github Actions if an action or something CI related was changed
      - '.github/workflows/**'
      - 'tools/ci/**'
      # This workflow should run when a file in a source directory has been modified.
      - 'src/**'
      - '3rdparty/**'
      # This workflow should run whenever a CMake related file has been modified
      - '**/CMakeLists.txt'

jobs:
  build:
    # Github Actions checks for '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', or '[actions skip]' but not a hyphenated version.
    # It's a catch-all incase a Pull Request has been opened and someone is on auto-pilot.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # The ubuntu-latest label currently points to ubuntu-22.04.
          # Available: ubuntu-22.04, ubuntu-20.04
          os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Create build directory
        run: mkdir cbuild

      - name: Configure project with CMake (C++20)
        run: |
          cd cbuild
          cmake -G "Unix Makefiles" -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-fmodules-ts" -stdlib=libc++ -fbuiltin-module-map -fimplicit-module-maps -fprebuilt-module-path="${CMAKE_BINARY_DIR}/modules" -DCMAKE_CXX_EXTENSIONS=OFF ..

      - name: Command - make
        run: |
          cd cbuild
          make
