name: Build servers in VIP mode
# build_servers_vip.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Always trigger all Github Actions if an action or something CI related was changed
      - '.github/workflows/**'
      - 'tools/ci/**'
      # This workflow should run when a file in a source directory has been modified.
      - 'src/**'
      - '3rdparty/**'

jobs:
  build:
    # Github Actions checks for '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', or '[actions skip]' but not a hyphenated version.
    # It's a catch-all incase a Pull Request has been opened and someone is on auto-pilot.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # The ubuntu-latest label currently points to ubuntu-22.04.
          # Available: ubuntu-22.04, ubuntu-20.04
          os: [ubuntu-latest]
          # Older versions of GCC are not available via unaltered aptitude repo lists.
          gcc: ['10','11','12']
          # We run build checks for both Renewal and PRE-Renewal
          mode: ['PRE', 'RE']
          include:
            - os: ubuntu-24.04
              gcc: 13

    steps:
      - uses: actions/checkout@v4

      # A simple 'yes' and 'no' can be confusing, so we use names to display in the current job then convert them for use in the compiler.
      - name: Variable Parsing - PRE
        if: ${{ matrix.mode == 'PRE' }} 
        run: |
          echo "PRERE=yes" >> $GITHUB_ENV
      - name: Variable Parsing - RE
        if: ${{ matrix.mode == 'RE' }} 
        run: |
          echo "PRERE=no" >> $GITHUB_ENV

      - name: Update & Install packages
        # Ubuntu runners already have most of the packages rAthena requires to build.
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
        run: |
          sudo apt update
          sudo apt install build-essential zlib1g-dev libpcre3-dev gcc-10 g++-10

      - name: Check endianess
        run: lscpu | grep "Byte Order"

      - name: Ensure configure has execution permissions
        run: chmod +x ./configure

      - name: Grant execute permissions to sql.sh
        run: chmod +x ./tools/ci/sql.sh

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Setup Database and import table data
        run: ./tools/ci/sql.sh

      - name: Command - configure
        if: ${{ matrix.mode == 'PRE' }} 
        run: |
          echo "PRERE=yes" >> $GITHUB_ENV

      - name: Checking Mode - PRE
        if: ${{ matrix.mode == 'PRE' }} 
        env:
          CONFIGURE_FLAGS: CC=gcc-10 CXX=g++-10 --enable-buildbot=yes --enable-prere --enable-vip

      - name: Checking Mode - RE
        if: ${{ matrix.mode == 'RE' }} 
        env:
          CONFIGURE_FLAGS: CC=gcc-10 CXX=g++-10 --enable-buildbot=yes --enable-vip
        run: ./configure $CONFIGURE_FLAGS CXXFLAGS="-std=c++20"
     
      - name: Show config.log for debugging
        run: cat config.log || true
 
      - name: Command - make clean
        run: make clean

      - name: Command - make server
        run: make server

      - name: Run Once - login-server
        run: ./login-server --run-once

      - name: Run Once - char-server
        run: ./char-server --run-once

      - name: Run Once - map-server
        run: ./map-server --run-once
